{% set name = "element-coder" %}
{% set version = "0.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/element_coder-{{ version }}.tar.gz
  sha256: 5a04e318368337e0e32197469d6e8f9c05e027c357a711c7094ac4cc7c93fbef

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - element_coder.encode = element_coder.cli:encode_cli
    - element_coder.decode = element_coder.cli:decode_cli



requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=35.0.2
    - setuptools_scm >=2.0.0,<3
  run:
    - python >={{ python_min }}
    - pymatgen
    - loguru
    - click

test:
  imports:
    - element_coder
  commands:
    - pip check
    - element_coder.encode --help
    - element_coder.decode --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kjappelbaum/element-coder
  summary: Encode chemical elements numerically and decode numerical representations of elements.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kjappelbaum
